name: Android Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Godot
        uses: firebelley/setup-godot@v2
        with:
          godot-version: "4.2.2"
          export-templates-version: "4.2.2"

      - name: Export Android Build
        run: |
          mkdir -p build/android
          godot --headless --export-release "Android" build/android/RiseOfSovereigns.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: RiseOfSovereigns-Android
          path: build/android/RiseOfSovereigns.apk
